version: '3.8'

services:
  backend:
    build:
      context: ./APIt
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ASPNETCORE_URLS=http://+:8000
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoDB=mongodb+srv://nazarena:naza.12345@cluster0.wjovzmn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0


