version: '3.8'

services:
  backend:
    build:
      context: ./APIt
      dockerfile: Dockerfile
    ports:
      - "5000:5001"
    environment:
      - ASPNETCORE_URLS=http://+:5001
      - ConnectionStrings__MongoDB=mongodb://mongodb:27017
    depends_on:
      - mongodb
    networks:
      - my_network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - my_network

networks:
  my_network:

volumes:
  mongodb_data: